### ISSUE TITLE
Can't connect to console

### ISSUE THREAD

**Issue by dgonzo** [benediktschmitt/emsm#35] opened 2014-11-26 23:23 UTC
When trying to invoke the --console command I get this:

>         NOTE: Press [ctrl + a + d] to detach from the console.
>         WARNING: When you stop the server in the session, EMSM may behave not as expected.
>Cannot open your terminal '/dev/pts/10' - please check.
>EMSM: Critical:
>> Exception: TypeError
>> Message:   expected string or buffer
>> A full traceback can be found in the log file.

**Comment by benediktschmitt** [comment] 2015-10-24 11:12
Sorry, that it took me so long to find this bug. I simply didn't see the cause of it. I think it is now fixed in the latest commit: bbbb9e7

**Closed** 2015-10-24 11:12 UTC
